export const identificationSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    likely_product_match: { type: 'string' },
    product_family: { type: 'string' },
    confidence: { type: 'string', enum: ['vysoka', 'stredni', 'nizka'] },
    identified_specs: { type: 'array', items: { type: 'string' } },
    likely_included_parts: { type: 'array', items: { type: 'string' } },
    detected_connectors: { type: 'array', items: { type: 'string' } },
    search_keywords: { type: 'array', items: { type: 'string' } },
    suggested_updates: {
      type: 'object',
      additionalProperties: false,
      properties: {
        brand: { type: 'string' },
        model: { type: 'string' },
        category: { type: 'string' },
        accessories: { type: 'string' },
        notes: { type: 'string' },
      },
      required: ['brand', 'model', 'category', 'accessories', 'notes'],
    },
    followup_questions: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          question: { type: 'string' },
          reason: { type: 'string' },
        },
        required: ['question', 'reason'],
      },
    },
  },
  required: [
    'likely_product_match',
    'product_family',
    'confidence',
    'identified_specs',
    'likely_included_parts',
    'detected_connectors',
    'search_keywords',
    'suggested_updates',
    'followup_questions',
  ],
}

export const analysisSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    product_summary: { type: 'string' },
    product_type_detected: { type: 'string' },
    estimated_condition: { type: 'string' },
    condition_confidence: { type: 'string', enum: ['vysoka', 'stredni', 'nizka'] },
    likely_product_match: { type: 'string' },
    identified_specs: { type: 'array', items: { type: 'string' } },
    likely_included_parts: { type: 'array', items: { type: 'string' } },
    detected_defects: { type: 'array', items: { type: 'string' } },
    missing_info: { type: 'array', items: { type: 'string' } },
    followup_questions: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          question: { type: 'string' },
          reason: { type: 'string' },
        },
        required: ['question', 'reason'],
      },
    },
    photo_assessment: {
      type: 'object',
      additionalProperties: false,
      properties: {
        quality: { type: 'string', enum: ['dobra', 'prumerna', 'spatna'] },
        count_sufficient: { type: 'boolean' },
        recommendations: { type: 'array', items: { type: 'string' } },
        missing_photos: { type: 'array', items: { type: 'string' } },
      },
      required: ['quality', 'count_sufficient', 'recommendations', 'missing_photos'],
    },
    warnings: { type: 'array', items: { type: 'string' } },
    positive_aspects: { type: 'array', items: { type: 'string' } },
  },
  required: [
    'product_summary',
    'product_type_detected',
    'estimated_condition',
    'condition_confidence',
    'likely_product_match',
    'identified_specs',
    'likely_included_parts',
    'detected_defects',
    'missing_info',
    'followup_questions',
    'photo_assessment',
    'warnings',
    'positive_aspects',
  ],
}

export const pricingSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    market_overview: { type: 'string' },
    price_range_min: { type: 'number' },
    price_range_max: { type: 'number' },
    price_fast_sale: { type: 'number' },
    price_balanced: { type: 'number' },
    price_premium: { type: 'number' },
    price_rationale: { type: 'string' },
    seller_price_assessment: {
      type: 'string',
      enum: ['prilis_vysoka', 'primerena', 'prilis_nizka', 'neuvedena'],
    },
    seller_price_comment: { type: 'string' },
    data_confidence: { type: 'string', enum: ['vysoka', 'stredni', 'nizka'] },
    data_note: { type: 'string' },
    price_factors: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          factor: { type: 'string' },
          impact: { type: 'string', enum: ['pozitivni', 'negativni', 'neutralni'] },
          description: { type: 'string' },
        },
        required: ['factor', 'impact', 'description'],
      },
    },
    comparable_items: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          description: { type: 'string' },
          price: { type: 'number' },
          platform: { type: 'string' },
        },
        required: ['description', 'price', 'platform'],
      },
    },
  },
  required: [
    'market_overview',
    'price_range_min',
    'price_range_max',
    'price_fast_sale',
    'price_balanced',
    'price_premium',
    'price_rationale',
    'seller_price_assessment',
    'seller_price_comment',
    'data_confidence',
    'data_note',
    'price_factors',
    'comparable_items',
  ],
}

export const generationSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    fast: { $ref: '#/$defs/listingVariant' },
    balanced: { $ref: '#/$defs/listingVariant' },
    premium: { $ref: '#/$defs/listingVariant' },
    improvements: { type: 'array', items: { type: 'string' } },
    risks: { type: 'array', items: { type: 'string' } },
  },
  required: ['fast', 'balanced', 'premium', 'improvements', 'risks'],
  $defs: {
    listingVariant: {
      type: 'object',
      additionalProperties: false,
      properties: {
        title: { type: 'string' },
        price: { type: 'number' },
        description: { type: 'string' },
        short_description: { type: 'string' },
        bullet_points: { type: 'array', items: { type: 'string' } },
        condition: { type: 'string' },
        category: { type: 'string' },
        keywords: { type: 'array', items: { type: 'string' } },
        delivery: { type: 'string' },
        payment: { type: 'string' },
        strategy_explanation: { type: 'string' },
      },
      required: [
        'title',
        'price',
        'description',
        'short_description',
        'bullet_points',
        'condition',
        'category',
        'keywords',
        'delivery',
        'payment',
        'strategy_explanation',
      ],
    },
  },
}
